import{useEffect,useMemo,useRef,useState}from'react';
import{createClient}from'genlayer-js';import{studionet}from'genlayer-js/chains';import{TransactionStatus}from'genlayer-js/types';
import{ArrowUpRight,BookOpen,CheckCircle2,GitBranch,GitCommit,Link2,Loader2,Plus,RefreshCw,ShieldCheck,X}from'lucide-react';
const ADDRESS=import.meta.env.VITE_CONTRACT_ADDRESS||'';const configured=/^0x[a-fA-F0-9]{40}$/.test(ADDRESS)&&!/^0x0{40}$/.test(ADDRESS);const EX='https://explorer-studio.genlayer.com';
const empty={mode:'root',parent:'0',title:'Archive command injection fix',property:'User-controlled archive paths must be passed as an argument vector without shell interpretation.',bo:'Azaria723',br:'PatchLineage',bc:'',bp:'/fixtures/upstream/vulnerable.py',bd:'',ao:'Azaria723',ar:'PatchLineage',ac:'',ap:'/fixtures/upstream/fixed.py',ad:''};
const short=v=>v?`${v.slice(0,7)}…${v.slice(-5)}`:'—';const source=(o,r,c,p,d)=>JSON.stringify({owner:o,repo:r,commit:c,path:p,digest:d});
function App(){const[nodes,setNodes]=useState([]),[selected,setSelected]=useState(null),[account,setAccount]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[readError,setReadError]=useState(''),[panel,setPanel]=useState(false),[guide,setGuide]=useState(false),[form,setForm]=useState(empty),[tx,setTx]=useState('');const lock=useRef(false);const read=()=>createClient({chain:studionet});
async function refresh(retries=2){if(!configured){setNodes([]);setLoading(false);return false}setLoading(true);setReadError('');let last;for(let attempt=0;attempt<=retries;attempt++){try{const client=read();const counts=JSON.parse(await client.readContract({address:ADDRESS,functionName:'get_counts',args:[]}));const list=[];for(let i=0;i<counts.node_count;i++)list.push(JSON.parse(await client.readContract({address:ADDRESS,functionName:'get_node',args:[BigInt(i)]})));setNodes(list);setSelected(current=>current==null?null:list.find(n=>n.node_id===current.node_id)||null);setLoading(false);return true}catch(e){last=e;if(attempt<retries)await new Promise(resolve=>setTimeout(resolve,1200*(attempt+1)))}}const message=`StudioNet readback unavailable: ${last?.message||'unknown RPC error'}`;setReadError(message);setNotice(message);setLoading(false);return false}
useEffect(()=>{refresh()},[]);async function connect(){if(!window.ethereum)return setNotice('Install an injected wallet to continue.');const[a]=await window.ethereum.request({method:'eth_requestAccounts'});setAccount(a);setNotice('Wallet connected. Writes remain under your confirmation.');}
async function write(fn,args){if(lock.current)return;lock.current=true;setBusy(true);setTx('');try{if(!configured)throw Error('Deployment address is not configured.');if(!account)throw Error('Connect a wallet first.');if(BigInt(await window.ethereum.request({method:'eth_chainId'}))!==61999n)throw Error('Switch to StudioNet chain 61999.');const client=createClient({chain:studionet,provider:window.ethereum,account});setNotice('Confirm the transaction in your wallet.');const hash=await client.writeContract({address:ADDRESS,functionName:fn,args});setTx(hash);setNotice('Submitted. Waiting for finalized consensus…');await read().waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED});const reconciled=await refresh(4);setNotice(reconciled?'Finalized and reconciled with authoritative contract state.':'Transaction finalized, but StudioNet readback is temporarily unavailable. Retry graph refresh.');}catch(e){setNotice(e.shortMessage||e.message)}finally{setBusy(false);lock.current=false}}
function submit(e){e.preventDefault();const before=source(form.bo,form.br,form.bc,form.bp,form.bd),after=source(form.ao,form.ar,form.ac,form.ap,form.ad);const args=form.mode==='root'?[form.title,form.property,before,after]:[BigInt(form.parent),form.title,before,after];write(form.mode==='root'?'create_fix_root':'submit_backport',args)}
const roots=nodes.filter(n=>n.parent_id===-1);const levels=useMemo(()=>{const map={};nodes.forEach(n=>(map[n.depth]??=[]).push(n));return map},[nodes]);return <div className="app">
<header><div className="brand"><img src="/patchlineage-logo.png"/><div><strong>PatchLineage</strong><span>SECURITY BACKPORT GRAPH</span></div></div><nav><button className="ghost" onClick={()=>setGuide(true)}><BookOpen/>How it works</button><a href="https://github.com/Azaria723/PatchLineage" target="_blank">GitHub <ArrowUpRight/></a><span className="network">● StudioNet · 61999</span><button className="connect" onClick={connect}>{account?short(account):'Connect wallet'}</button></nav></header>
<main><section className="intro"><div><p className="eyebrow">VERIFIABLE PATCH PROVENANCE</p><h1>Trace a security fix<br/>across every fork.</h1><p>Build a public lineage of semantically equivalent backports. Exact source provenance meets validator consensus.</p></div><div className="actions"><button className="primary" onClick={()=>setPanel(true)}><Plus/>Submit node</button><button className="refresh" onClick={refresh}><RefreshCw/>Refresh graph</button></div></section>
<section className="metrics"><div><span>ROOT FIXES</span><b>{roots.length}</b></div><div><span>GRAPH NODES</span><b>{nodes.length}</b></div><div><span>CERTIFIED</span><b>{nodes.filter(n=>n.status==='CERTIFIED').length}</b></div><div><span>CONTRACT</span><b>{configured?short(ADDRESS):'Awaiting deploy'}</b></div></section>
<section className="workspace"><div className="workspace-head"><div><p className="eyebrow">LINEAGE CANVAS</p><h2>Certification graph</h2></div><span>Click a node to inspect immutable sources</span></div>{loading?<div className="empty"><Loader2 className="spin"/><h3>Reading StudioNet state</h3><p>The graph appears only after authoritative contract readback completes.</p></div>:readError?<div className="empty error-state"><RefreshCw/><h3>Graph readback unavailable</h3><p>{readError}</p><button onClick={()=>refresh()}>Retry StudioNet readback</button></div>:nodes.length?<div className="graph">{Object.keys(levels).map(depth=><div className="level" key={depth}><label>DEPTH {depth}</label><div className="node-row">{levels[depth].map(n=><button key={n.node_id} className={`node ${n.status.toLowerCase()} ${selected?.node_id===n.node_id?'active':''}`} onClick={()=>setSelected(n)}><div className="node-top"><span>PL-{String(n.node_id).padStart(3,'0')}</span><i>{n.status}</i></div><h3>{n.title}</h3><p>{n.classification}</p><div><GitBranch/> parent {n.parent_id===-1?'ROOT':`PL-${String(n.parent_id).padStart(3,'0')}`}</div></button>)}</div></div>)}</div>:<div className="empty"><GitBranch/><h3>No lineage exists yet</h3><p>Create a root security fix after deployment, then attach independently verified backports.</p><button onClick={()=>setPanel(true)}>Open submission workspace</button></div>}</section>
{notice&&<div className="notice">{busy&&<Loader2 className="spin"/>}{notice}{tx&&<a href={`${EX}/tx/${tx}`} target="_blank">View transaction <ArrowUpRight/></a>}</div>}
</main>{selected&&<aside className="inspector"><button className="close" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">NODE INSPECTOR</p><h2>{selected.title}</h2><div className={`verdict ${selected.status.toLowerCase()}`}><ShieldCheck/><span>{selected.status}<small>{selected.classification}</small></span></div><dl><dt>Node</dt><dd>PL-{String(selected.node_id).padStart(3,'0')}</dd><dt>Parent</dt><dd>{selected.parent_id===-1?'Root':`PL-${String(selected.parent_id).padStart(3,'0')}`}</dd><dt>Depth</dt><dd>{selected.depth}</dd><dt>Submitter</dt><dd>{short(selected.submitter)}</dd><dt>Confidence</dt><dd>{selected.confidence||'Pending'}</dd></dl><h4><GitCommit/> Immutable sources</h4><a href={`https://github.com/${selected.before.owner}/${selected.before.repo}/blob/${selected.before.commit}${selected.before.path}`} target="_blank">Before · {short(selected.before.commit)} <ArrowUpRight/></a><a href={`https://github.com/${selected.after.owner}/${selected.after.repo}/blob/${selected.after.commit}${selected.after.path}`} target="_blank">After · {short(selected.after.commit)} <ArrowUpRight/></a>{selected.status==='PENDING'&&<button className="primary full" onClick={()=>write('assess_node',[BigInt(selected.node_id)])}><ShieldCheck/>Assess node</button>}</aside>}
{panel&&<div className="overlay"><form className="form-panel" onSubmit={submit}><div className="form-head"><div><p className="eyebrow">SUBMISSION WORKSPACE</p><h2>Register immutable source pair</h2></div><button type="button" className="close" onClick={()=>setPanel(false)}><X/></button></div><div className="switch"><button type="button" className={form.mode==='root'?'on':''} onClick={()=>setForm({...form,mode:'root'})}>Root fix</button><button type="button" className={form.mode==='backport'?'on':''} onClick={()=>setForm({...form,mode:'backport'})}>Backport edge</button></div>{form.mode==='backport'&&<Field label="Certified parent ID" value={form.parent} set={v=>setForm({...form,parent:v})}/>}<Field label="Title" value={form.title} set={v=>setForm({...form,title:v})}/>{form.mode==='root'&&<label>Security property<textarea value={form.property} onChange={e=>setForm({...form,property:e.target.value})}/></label>}<SourceFields label="BEFORE SOURCE" prefix="b" form={form} setForm={setForm}/><SourceFields label="AFTER SOURCE" prefix="a" form={form} setForm={setForm}/><button className="primary submit" disabled={busy}><Link2/>{form.mode==='root'?'Create root candidate':'Attach backport candidate'}</button></form></div>}
{guide&&<div className="overlay"><div className="guide"><button className="close" onClick={()=>setGuide(false)}><X/></button><p className="eyebrow">HOW IT WORKS</p><h2>Bytes first. Meaning second. Graph last.</h2>{[['01','Bind','Each source is locked to repository, full commit, path and SHA-256.'],['02','Verify','Validators recompute commit, tree, blob and byte-level provenance.'],['03','Judge','Comparative consensus checks whether the security property is fully preserved.'],['04','Connect','Only certified nodes may become parents in the backport DAG.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><p>{x[2]}</p></span></div>)}</div></div>}</div>}
function Field({label,value,set}){return <label>{label}<input value={value} onChange={e=>set(e.target.value)}/></label>};function SourceFields({label,prefix,form,setForm}){const u=k=>`${prefix}${k}`;return <fieldset><legend>{label}</legend><div className="two"><Field label="GitHub owner" value={form[u('o')]} set={v=>setForm({...form,[u('o')]:v})}/><Field label="Repository" value={form[u('r')]} set={v=>setForm({...form,[u('r')]:v})}/></div><Field label="Full commit SHA" value={form[u('c')]} set={v=>setForm({...form,[u('c')]:v})}/><Field label="Canonical path" value={form[u('p')]} set={v=>setForm({...form,[u('p')]:v})}/><Field label="SHA-256" value={form[u('d')]} set={v=>setForm({...form,[u('d')]:v})}/></fieldset>}
export default App;
